### ISSUE TITLE
Ошибка коннекта с ldap

### ISSUE THREAD

**Issue by Vovaman** [Vovaman/peresvet#127]

**Comment by Vovaman** [comment]
При потере связи с ldap появляется необрабатываемая ошибка: 
```console
one_app        | Traceback (most recent call last):
one_app        | 
one_app        |   File "/usr/local/lib/python3.10/site-packages/ldap/ldapobject.py", line 972, in _apply_method_s
one_app        |     return func(self,*args,**kwargs)
one_app        |            │    │     │      └ {}
one_app        |            │    │     └ ('cn=admin,cn=prs', 'Peresvet21', None, None)
one_app        |            │    └ <ldappool.StateConnector object at 0x726db7d7fa00>
one_app        |            └ <function SimpleLDAPObject.simple_bind_s at 0x726ded977b50>
one_app        |   File "/usr/local/lib/python3.10/site-packages/ldap/ldapobject.py", line 248, in simple_bind_s
one_app        |     msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
one_app        |             │    │           │   │    │           └ None
one_app        |             │    │           │   │    └ None
one_app        |             │    │           │   └ 'Peresvet21'
one_app        |             │    │           └ 'cn=admin,cn=prs'
one_app        |             │    └ <function SimpleLDAPObject.simple_bind at 0x726ded977ac0>
one_app        |             └ <ldappool.StateConnector object at 0x726db7d7fa00>
one_app        |   File "/usr/local/lib/python3.10/site-packages/ldap/ldapobject.py", line 242, in simple_bind
one_app        |     return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
one_app        |            │    │          │                   │   │    │                    │            │                    └ None
one_app        |            │    │          │                   │   │    │                    │            └ <function RequestControlTuples at 0x726ded8e83a0>
one_app        |            │    │          │                   │   │    │                    └ None
one_app        |            │    │          │                   │   │    └ <function RequestControlTuples at 0x726ded8e83a0>
one_app        |            │    │          │                   │   └ 'Peresvet21'
one_app        |            │    │          │                   └ 'cn=admin,cn=prs'
one_app        |            │    │          └ <ldappool.StateConnector object at 0x726db7d7fa00>
one_app        |            │    └ <function SimpleLDAPObject._ldap_call at 0x726ded977400>
one_app        |            └ <ldappool.StateConnector object at 0x726db7d7fa00>
one_app        |   File "/usr/local/lib/python3.10/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
one_app        |     result = func(*args,**kwargs)
one_app        |              │     │      └ {}
one_app        |              │     └ ('cn=admin,cn=prs', 'Peresvet21', None, None)
one_app        |              └ <built-in method simple_bind of LDAP object at 0x726db7d7e370>
one_app        | 
one_app        | ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'errno': 107, 'ctrls': [], 'info': 'Transport endpoint is not connected'}
```
